### ISSUE TITLE
Players used in Suggestion should be allowed to stay in room

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#17]
If a player is already in a room from last turn and was used in an opponent’s Suggestion in the same room since last turn, they should not be allowed to stay and make another Suggestion in same room

**Comment by JenTzori** [comment]
I typed this up to move it over from the target increment doc, but I think I disagree that this is a bug. Are we counting this case as a player **not** moved into the room since their last turn?

@megmello @dfpreston @BernardVerna @ktrages1 Thoughts?

**Comment by megmello** [comment]
Okay... so this is a bit nuanced.  Jen is pointing out a third case.
1. If move into a room on own turn... have option to make a Suggestion.
2. If moved into a room as suspect in opponent's Suggestion since own last turn, have option to stay in room and make a Suggestion.
   "If the suspect transferred was your own character pawn, you may, on your next turn, do one of two things: Move from the room in one of the usual ways OR make a Suggestion for that room.  If you decide to make a Suggestion, do not move your character pawn."
3. If previously in room from own turn and used in opponent's Suggestion (but not _transferred_ for it), seems like should not get an automatic option to Suggest.  Would need to move out of current room.

I think the flag for whether token had been moved into room for opponent's Suggestion is being set to true upon character's use in Suggestion.  Instead, only set to true if not already in room.

Agree?

**Comment by megmello** [comment]
Guessing change would be at game_manager.py, lines 217-218.

**Comment by ktrages1** [comment]
@megmello I think you're right. Added a check to see if the player was already in the room.

**Comment by JenTzori** [comment]
Confirmed this in runthrough today. Closing.
